// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEot0agWlGGcTrX8Miq4rEl-PSQ42CJEo',
    appId: '1:976090297827:web:c586123a5c953353095cd6',
    messagingSenderId: '976090297827',
    projectId: 'entrelacos-387103',
    authDomain: 'entrelacos-387103.firebaseapp.com',
    storageBucket: 'entrelacos-387103.appspot.com',
    measurementId: 'G-93JYWHTDLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfnN7SjHevyzuzYdeXwbySQJSkcy5wIR8',
    appId: '1:976090297827:android:3e867a53df992267095cd6',
    messagingSenderId: '976090297827',
    projectId: 'entrelacos-387103',
    storageBucket: 'entrelacos-387103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3I_Echi0Bd9algTT--MauJp8KH9MloY',
    appId: '1:976090297827:ios:e14de1879bfd06f5095cd6',
    messagingSenderId: '976090297827',
    projectId: 'entrelacos-387103',
    storageBucket: 'entrelacos-387103.appspot.com',
    iosClientId: '976090297827-t9ja62edtlc1c2iahbei83j1b7f2i9r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.entrelacosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3I_Echi0Bd9algTT--MauJp8KH9MloY',
    appId: '1:976090297827:ios:8532a066e21e0951095cd6',
    messagingSenderId: '976090297827',
    projectId: 'entrelacos-387103',
    storageBucket: 'entrelacos-387103.appspot.com',
    iosClientId: '976090297827-0od6cnveg1lhe4udor9p2d8rlhas8l5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.entrelacosApp.RunnerTests',
  );
}
